name: Frontend unit tests
description: 'Run frontend unit tests'
runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1

    - name: Install
      shell: bash
      run: cd frontend && bun run install

    - name: Run unit tests
      shell: bash
      run: cd frontend && bun run test:unit
