CREATE TABLE urls (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    original_url VARCHAR(255) NOT NULL UNIQUE,
    short_url TEXT NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 week',
    usage INT DEFAULT 0
);