DROP TABLE users IF EXIST;

CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    picture VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);