DROP TABLE url_user IF EXIST;

CREATE TABLE url_user (
    id UUID PRIMARY KEY DEFAULT UUID(),
    user_id UUID NOT NULL,
    url_id UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE ON UPDATE CASCADE
);